import sharp from 'sharp';

/**
 * In-memory buffer store for uploaded media artifacts
 */
export const artifactMediaStore = new Map();

export function storeArtifactMedia(artifactId, { buffer, mimeType, filename, originalName }) {
  if (!artifactId || !buffer) return null;
  const base64 = buffer.toString('base64');
  const dataUrl = `data:${mimeType || 'image/jpeg'};base64,${base64}`;
  const record = {
    id: artifactId,
    buffer,
    mimeType: mimeType || 'image/jpeg',
    filename: filename || 'media_artifact.jpg',
    originalName: originalName || filename || 'media_artifact.jpg',
    byteSize: buffer.length,
    dataUrl,
    storedAt: new Date().toISOString()
  };
  artifactMediaStore.set(artifactId, record);
  return record;
}

export function getArtifactMedia(artifactId) {
  return artifactMediaStore.get(artifactId) || null;
}

/**
 * Computes deep pixel, channel, and entropy statistics using Sharp.
 */
export async function computeImageStatistics(imageBuffer) {
  if (!imageBuffer || !Buffer.isBuffer(imageBuffer)) {
    return null;
  }
  try {
    const img = sharp(imageBuffer);
    const meta = await img.metadata();
    const stats = await img.stats();

    // Compute luminance metrics
    const channels = stats.channels.map((c, idx) => ({
      index: idx,
      name: idx === 0 ? 'R' : idx === 1 ? 'G' : idx === 2 ? 'B' : 'A',
      min: c.min,
      max: c.max,
      mean: Number(c.mean.toFixed(2)),
      stdev: Number(c.stdev.toFixed(2)),
      entropy: Number((Math.log2(c.stdev + 1) * 1.4).toFixed(2))
    }));

    const isGrayscale = stats.isOpaque && channels.length >= 3 &&
      Math.abs(channels[0].mean - channels[1].mean) < 2 &&
      Math.abs(channels[1].mean - channels[2].mean) < 2;

    const meanLuminance = channels.length >= 3
      ? Number((0.299 * channels[0].mean + 0.587 * channels[1].mean + 0.114 * channels[2].mean).toFixed(2))
      : (channels[0]?.mean || 0);

    const meanVariance = channels.length >= 3
      ? Number(((channels[0].stdev + channels[1].stdev + channels[2].stdev) / 3).toFixed(2))
      : (channels[0]?.stdev || 0);

    return {
      format: meta.format || 'unknown',
      width: meta.width || 0,
      height: meta.height || 0,
      space: meta.space || 'srgb',
      channels: meta.channels || 3,
      depth: meta.depth || 'uchar',
      density: meta.density || 72,
      hasAlpha: Boolean(meta.hasAlpha),
      isOpaque: Boolean(stats.isOpaque),
      isGrayscale,
      meanLuminance,
      meanVariance,
      channelStats: channels,
      dominant: stats.dominant || null,
      entropy: stats.entropy ? Number(stats.entropy.toFixed(2)) : Number((meanVariance / 10).toFixed(2))
    };
  } catch (err) {
    console.warn('[SharpStats] Failed to compute image statistics:', err.message);
    return null;
  }
}

/**
 * Multimodal AI Vision Forensic Analysis using Gemini Vision.
 * Passes the actual image binary to Gemini to inspect photographic realism,
 * AI generation signatures, face manipulation, and visual inconsistencies.
 */
export async function runGeminiMultimodalForensicVision({
  buffer,
  mimeType = 'image/jpeg',
  filename = 'image.jpg',
  exif = null,
  elaResult = null,
  statsResult = null,
  callGeminiFn
}) {
  if (!buffer || !callGeminiFn) {
    return null;
  }

  const prompt = `You are the VeriMedia AI Chief Multimodal Media Forensic Analyst.
You are directly visually inspecting this user-uploaded media image: "${filename}".

Inspect the physical visual elements, pixel layout, illumination, textures, anatomy, and metadata to provide an authoritative, grounded forensic assessment.

Extracted Technical Context:
- Dimensions: ${statsResult ? `${statsResult.width}x${statsResult.height}` : 'Unknown'}
- Format: ${statsResult?.format || mimeType}
- Color Space: ${statsResult?.space || 'sRGB'} (Channels: ${statsResult?.channels || 3})
- Mean Luminance: ${statsResult?.meanLuminance ?? 'N/A'}, Variance: ${statsResult?.meanVariance ?? 'N/A'}
- ELA Status: ${elaResult ? `${elaResult.status} (Mean Error: ${elaResult.meanError ?? 0}, Max: ${elaResult.maxError ?? 0}, Anomaly: ${elaResult.hasCompressionAnomaly ? 'YES' : 'NO'})` : 'Not computed'}
- EXIF Status: ${exif ? `Camera: ${exif.Make || ''} ${exif.Model || ''}, Software: ${exif.Software || 'None'}, Date: ${exif.DateTimeOriginal || 'N/A'}` : 'EXIF Stripped / None'}

Carefully evaluate the image for:
1. SUBJECT & CONTENT: What is actually visible and depicted in this image? (Describe the scene, subjects, objects, lighting).
2. AI SYNTHETIC / GENERATIVE DETECTION: Is this image generated by generative AI (Midjourney, DALL-E, Stable Diffusion, Flux, Imagen, etc.)? Look for prompt-leakage textures, diffusion noise distribution, missing skin pores, hallucinated fingers/limbs, nonsensical background structures, synthetic glossiness.
3. DEEPFAKE & MANIPULATION: Are there signs of face swap, localized inpainting, splicing, or warping along boundaries? Look for misaligned eye specular highlights, blurred jawlines, mismatched skin tones.
4. AUTHENTIC PHOTOGRAPHY: If the image is a genuine real camera photograph or artwork, confirm that optical depth of field, natural lens bokeh, sensor noise grain, and light bounce obey physics.
5. CALIBRATED FORENSIC SCORES (0.00 to 1.00 for each):
   - spatial_diff: localized pixel inconsistency / splicing
   - noise_score: sensor noise PRNU irregularity
   - color_diff: chroma subsampling & white balance anomalies
   - face_landmark: facial geometry and alignment deformation
   - jpeg_artifact: compression block and quantization inconsistencies
   - edge_consistency: boundary sharpness and gradient coherence (1.0 = highly coherent natural edges)
   - temporal_mismatch: motion blur vs shutter speed mismatch
   - watermark_detected: 1.0 if watermarks/logos are present, 0.0 otherwise

Return STRICT JSON only (no markdown, no extra commentary):
{
  "subject_description": "Precise 1-sentence description of what is actually depicted in this image",
  "authenticity": "GENUINE" | "AI_GENERATED" | "DEEPFAKE_MANIPULATED" | "SPLICED_COMPOSITE" | "TAMPERED",
  "trust_score": integer between 0 and 100 (e.g. 85-98 for authentic natural photo, 10-35 for AI generated or deepfake),
  "manipulation_probability": float between 0.00 and 1.00,
  "confidence": float between 0.70 and 0.98,
  "verdict": "Clear 1-sentence summary verdict",
  "summary": "2-3 sentence executive forensic summary detailing specific visual evidence observed in this exact image",
  "visual_findings": [
    "Specific observation 1 about textures, lighting, subject in this image",
    "Specific observation 2 about background, optical properties, or AI artifacts",
    "Specific observation 3 about edge gradients, noise grain, or compression"
  ],
  "signals": {
    "spatial_diff": float 0.0-1.0,
    "noise_score": float 0.0-1.0,
    "color_diff": float 0.0-1.0,
    "face_landmark": float 0.0-1.0,
    "jpeg_artifact": float 0.0-1.0,
    "edge_consistency": float 0.0-1.0,
    "temporal_mismatch": float 0.0-1.0,
    "watermark_detected": float 0.0-1.0
  },
  "detected_anomalies": [
    "Anomaly description 1 or 'None detected - natural optical physics confirmed'"
  ],
  "risk_level": "LOW" | "MEDIUM" | "HIGH" | "CRITICAL",
  "recommended_action": "ALLOW" | "REQUEST_ATTRIBUTION" | "SEND_DMCA_TAKEDOWN" | "EMERGENCY_TAKEDOWN",
  "dmca_needed": boolean
}`;

  try {
    const contents = [
      {
        role: 'user',
        parts: [
          {
            inlineData: {
              mimeType: mimeType || 'image/jpeg',
              data: buffer.toString('base64')
            }
          },
          {
            text: prompt
          }
        ]
      }
    ];

    const res = await callGeminiFn(contents, {
      responseMimeType: 'application/json',
      temperature: 0.15
    });

    if (res && res.text) {
      const parsed = JSON.parse(res.text);
      return {
        ...parsed,
        source: 'LLM_VISION_OPINION',
        engine: `Gemini Vision (${res.model || 'multimodal'})`,
        limitations: [
          'LLM vision judgments represent subjective probabilistic visual interpretations, not a calibrated deepfake detection model with validated false positive/negative rates.',
          'Uncalibrated confidence and trust scores cannot be interpreted as definitive mathematical probabilities of manipulation.',
          'Adversarial perturbations, diffusion noise patterns, and refined inpainting can deceive multimodal LLMs.',
          'Definitive authenticity verification requires end-to-end cryptographic provenance (C2PA / hardware digital signatures).'
        ]
      };
    }
  } catch (err) {
    console.warn('[GeminiVisionForensics] AI multimodal vision analysis failed:', err.message);
  }

  return null;
}

/**
 * Perform Error-Level Analysis (ELA) on an image buffer.
 * Recompresses to JPEG at 90% quality and computes pixel-level absolute difference.
 */
export async function performErrorLevelAnalysis(imageBuffer, mimeType = 'image/jpeg') {
  if (!imageBuffer || !Buffer.isBuffer(imageBuffer)) {
    return {
      status: 'SKIPPED',
      reason: 'No image buffer provided',
      observations: []
    };
  }

  const isJpeg = mimeType === 'image/jpeg' || mimeType === 'image/jpg';
  if (!isJpeg) {
    return {
      status: 'NOT_APPLICABLE',
      reason: 'Error-Level Analysis requires JPEG compression artifacts (DCT quantization blocks). Non-JPEG formats are not applicable.',
      isJpeg: false,
      limitations: [
        'ELA is strictly formulated for discrete cosine transform (DCT) compression grids.',
        'Formats such as PNG, WebP, SVG, and GIF do not share JPEG error decay characteristics.'
      ],
      observations: []
    };
  }

  try {
    const original = sharp(imageBuffer);
    const meta = await original.metadata();
    if (!meta.width || !meta.height) {
      return { status: 'ERROR', reason: 'Unable to decode image dimensions for ELA' };
    }

    // Limit maximum dimension to 1200px to bound processing time while preserving block grids
    const maxDim = Math.max(meta.width, meta.height);
    const scale = maxDim > 1200 ? 1200 / maxDim : 1.0;
    const targetW = Math.round(meta.width * scale);
    const targetH = Math.round(meta.height * scale);

    // Get raw RGB of original
    const origRaw = await original
      .resize(targetW, targetH, { fit: 'fill' })
      .toFormat('raw')
      .toBuffer();

    // Recompress at 90% JPEG quality
    const recompressedJpeg = await sharp(imageBuffer)
      .resize(targetW, targetH, { fit: 'fill' })
      .jpeg({ quality: 90 })
      .toBuffer();

    // Get raw RGB of recompressed
    const recompRaw = await sharp(recompressedJpeg)
      .toFormat('raw')
      .toBuffer();

    const minLen = Math.min(origRaw.length, recompRaw.length);
    let totalError = 0;
    let maxError = 0;
    const sampleSize = Math.floor(minLen / 3); // 3 channels RGB
    let highErrorPixelCount = 0;

    for (let i = 0; i < minLen; i += 3) {
      const diffR = Math.abs(origRaw[i] - recompRaw[i]);
      const diffG = Math.abs(origRaw[i + 1] - recompRaw[i + 1]);
      const diffB = Math.abs(origRaw[i + 2] - recompRaw[i + 2]);
      const pixelErr = (diffR + diffG + diffB) / 3;

      totalError += pixelErr;
      if (pixelErr > maxError) maxError = pixelErr;
      if (pixelErr > 25.0) {
        highErrorPixelCount++;
      }
    }

    const meanError = sampleSize > 0 ? totalError / sampleSize : 0;
    const highErrorRatio = sampleSize > 0 ? highErrorPixelCount / sampleSize : 0;

    // Determine ELA indication based on error variance
    const hasCompressionAnomaly = highErrorRatio > 0.08 && maxError > 45;
    const confidence = Math.min(0.92, Math.max(0.40, Number((0.50 + Math.abs(meanError - 10) / 40).toFixed(2))));

    return {
      status: 'COMPLETED',
      isJpeg: true,
      meanError: Number(meanError.toFixed(2)),
      maxError: Number(maxError.toFixed(2)),
      highErrorRatio: Number((highErrorRatio * 100).toFixed(2)),
      hasCompressionAnomaly,
      confidence,
      assessment: hasCompressionAnomaly
        ? 'High localized error discrepancy observed; indicates potential multi-generation compression or spliced elements.'
        : 'Uniform error-level dissipation across image surface; consistent with single-generation compression.',
      limitations: [
        'ELA identifies compression inconsistencies across surfaces, not intentional maliciousness.',
        'Does not detect neural generative synthesis (AI deepfakes, diffusion generation) that lacks splicing seams.',
        'High-contrast edges and solid geometric borders naturally produce elevated error levels.'
      ]
    };
  } catch (err) {
    return {
      status: 'ERROR',
      reason: `ELA computation error: ${err.message}`,
      observations: []
    };
  }
}

/**
 * Analyzes EXIF metadata for tampering, editing software, and timestamp contradictions.
 */
export function analyzeExifMetadata(exif) {
  if (!exif || Object.keys(exif).length === 0) {
    return {
      status: 'NO_EXIF_PRESENT',
      softwareDetected: null,
      timestampAnomaly: false,
      missingDeviceData: true,
      flags: ['EXIF_STRIPPED_OR_ABSENT'],
      observations: [
        {
          type: 'EXIF_METADATA_STATUS',
          value: 'Metadata absent or stripped by social compression',
          confidence: 0.95
        }
      ],
      limitations: [
        'Most modern social platforms (X, Facebook, Instagram, Reddit) automatically strip EXIF metadata on upload.',
        'Absence of EXIF is standard on web-distributed media and does not prove fabrication.'
      ]
    };
  }

  const flags = [];
  const observations = [];

  // 1. Software signature check
  const software = exif.Software || exif.ProcessingSoftware || exif.SoftwareAgent || '';
  const knownEditors = [
    'photoshop', 'gimp', 'canva', 'lightroom', 'after effects',
    'premiere', 'snapseed', 'paint.net', 'affinity', 'picsart', 'pixlr'
  ];

  let softwareDetected = null;
  if (typeof software === 'string' && software.trim().length > 0) {
    const lower = software.toLowerCase();
    const matched = knownEditors.find(ed => lower.includes(ed));
    if (matched) {
      softwareDetected = software;
      flags.push(`EDITING_SOFTWARE_DETECTED: ${software}`);
      observations.push({
        type: 'SOFTWARE_METADATA_SIGNATURE',
        value: `Image metadata records editing application: ${software}`,
        confidence: 0.92
      });
    } else {
      observations.push({
        type: 'SOFTWARE_METADATA_SIGNATURE',
        value: `Software tag present: ${software}`,
        confidence: 0.85
      });
    }
  }

  // 2. Timestamp consistency check
  const createDate = exif.DateTimeOriginal || exif.CreateDate;
  const modifyDate = exif.ModifyDate || exif.DateTime;
  let timestampAnomaly = false;

  if (createDate && modifyDate) {
    const cTime = new Date(createDate).getTime();
    const mTime = new Date(modifyDate).getTime();

    if (!isNaN(cTime) && !isNaN(mTime)) {
      const diffMinutes = (mTime - cTime) / (1000 * 60);
      if (diffMinutes > 5) {
        timestampAnomaly = true;
        flags.push(`MODIFY_DATE_AFTER_ORIGINAL: ${Math.round(diffMinutes)} minutes discrepancy`);
        observations.push({
          type: 'TIMESTAMP_DISCREPANCY',
          value: `Modification timestamp is ${Math.round(diffMinutes)} minutes later than original capture timestamp`,
          confidence: 0.90
        });
      }
    }
  }

  // 3. Device provenance check
  const make = exif.Make;
  const model = exif.Model;
  const hasDevice = Boolean(make || model);

  if (hasDevice) {
    observations.push({
      type: 'CAMERA_DEVICE_METADATA',
      value: `Recorded capture hardware: ${make || 'Unknown'} ${model || ''}`.trim(),
      confidence: 0.88
    });
  } else {
    flags.push('MISSING_HARDWARE_METADATA');
  }

  return {
    status: 'ANALYZED',
    softwareDetected,
    timestampAnomaly,
    missingDeviceData: !hasDevice,
    flags,
    observations,
    limitations: [
      'EXIF headers can be altered or injected using common tools (exiftool).',
      'Presence of editing software can indicate simple cropping or format export, not necessarily deceptive forgery.'
    ]
  };
}
